version: '3.9'

services:
  wordpress:
    image: wordpress:php8.1-fpm
    ports:
      - "8080:80"
      - "9000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: default_user
      WORDPRESS_DB_PASSWORD: random_password
      WORDPRESS_DB_NAME: default_database
    volumes:
      - wordpress-data:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: default_database
      MYSQL_USER: default_user
      MYSQL_PASSWORD: random_password
      MYSQL_ROOT_PASSWORD: random_password
    volumes:
      - db-data:/var/lib/mysql

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - wordpress-data:/var/www/html
    depends_on:
      - wordpress

volumes:
  wordpress-data:
  db-data:
